### ISSUE TITLE
Navbar Jenkins text should link to app not be hardcodedJenkins.io

### ISSUE THREAD

**Issue by timja** [halkeye/jenkins-io-components#15]
Jenkins link in top left should be customise-able for the destination so that users clicking it stay in the same app.

e.g. for account app it should be https://accounts.jenkins.io, (it should really be relative too so that in local dev you don't accidentally go to production).

<img width="808" alt="image" src="https://user-images.githubusercontent.com/21194782/196062112-bf9f786c-a4e3-498a-a3eb-6616393e298f.png">

also see https://github.com/jenkins-infra/account-app/issues/149

cc @halkeye

**Comment by halkeye** [comment]
> it should really be relative too so that in local dev you don't accidentally go to productio

yea you are right, should always just be /

**Comment by timja** [comment]
yeah that should work just fine
